"""inital migration

Revision ID: 7654f336dff9
Revises:
Create Date: 2023-07-17 22:09:56.873752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7654f336dff9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('ombi_url', sa.String(), nullable=True),
    sa.Column('ombi_api_key', sa.String(), nullable=True),
    sa.Column('qbittorrent_url', sa.String(), nullable=True),
    sa.Column('qbittorrent_username', sa.String(), nullable=True),
    sa.Column('qbittorrent_password', sa.String(), nullable=True),
    sa.Column('tautulli_url', sa.String(), nullable=True),
    sa.Column('tautulli_api_key', sa.String(), nullable=True),
    sa.Column('radarr_url', sa.String(), nullable=True),
    sa.Column('radarr_api_key', sa.String(), nullable=True),
    sa.Column('sonarr_url', sa.String(), nullable=True),
    sa.Column('sonarr_api_key', sa.String(), nullable=True),
    sa.Column('smtp_server', sa.String(), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_sender', sa.String(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=True),
    sa.Column('smtp_password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_config_created_at'), 'app_config', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_default_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_app_config_created_at'), table_name='app_config')
    op.drop_table('app_config')
    # ### end Alembic commands ###
