"""added overseerr config params

Revision ID: 7a4bf49af6df
Revises: 3dea3e826fa2
Create Date: 2023-09-23 16:36:25.169071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4bf49af6df'
down_revision = '3dea3e826fa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_config', sa.Column('overseerr_url', sa.String(), nullable=True))
    op.add_column('app_config', sa.Column('overseerr_api_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_config', 'overseerr_api_key')
    op.drop_column('app_config', 'overseerr_url')
    # ### end Alembic commands ###
