"""added expired media ignored items

Revision ID: 7ba4d91f4124
Revises: 7654f336dff9
Create Date: 2023-07-20 18:23:28.829205

"""
import json
import os
from uuid import uuid4
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm.session import Session

from mediamanager.app import CONFIG_DIR


# revision identifiers, used by Alembic.
revision = "7ba4d91f4124"
down_revision = "7654f336dff9"
branch_labels = None
depends_on = None


def import_existing_ignored_items(ignored_items_table: sa.Table, session: Session):
    """Migrate from old JSON file to new database schema"""

    if not os.path.exists(json_path := os.path.join(CONFIG_DIR, "expired_media_ignore.json")):
        return

    try:
        with open(json_path) as fp:
            ignored_items: list[dict] = json.load(fp)

        op.bulk_insert(ignored_items_table, [item | {"id": str(uuid4())} for item in ignored_items["items"]])
        session.commit()

        os.rename(json_path, f"{json_path}.imported")

    except Exception:
        return


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ignored_items_table = op.create_table(
        "expired_media_ignored_item",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rating_key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expired_media_ignored_item_created_at"), "expired_media_ignored_item", ["created_at"], unique=False
    )
    # ### end Alembic commands ###

    session = Session(bind=op.get_bind())
    import_existing_ignored_items(ignored_items_table, session)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expired_media_ignored_item_created_at"), table_name="expired_media_ignored_item")
    op.drop_table("expired_media_ignored_item")
    # ### end Alembic commands ###
