"""added expired media ignored items

Revision ID: 7ba4d91f4124
Revises: 7654f336dff9
Create Date: 2023-07-20 18:23:28.829205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7ba4d91f4124"
down_revision = "7654f336dff9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "expired_media_ignored_item",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("rating_key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_expired_media_ignored_item_created_at"), "expired_media_ignored_item", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expired_media_ignored_item_created_at"), table_name="expired_media_ignored_item")
    op.drop_table("expired_media_ignored_item")
    # ### end Alembic commands ###
